name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  deploy:
    if: always()
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
    - uses: actions/download-artifact@master
      with:
        name: playwright-report
        path: playwright-report/
    - uses: actions/configure-pages@main
    - uses: actions/upload-pages-artifact@main
      with:
        path: './playwright-report/'
    - id: deployment
      uses: actions/deploy-pages@main

  # slack-notification:
  #   if: always()
  #   name: 'Send Slack notification'
  #   runs-on: ubuntu-latest
  #   needs: deploy
  #   steps:
  #     - name: Download test artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         path: test-artifacts

  #     - name: 'Send Slack notification'
  #       uses: automattic/action-test-results-to-slack@v0.2.1
  #       with:
  #         github_token: ${{ secrets.TOKEN_GITHUB }}
  #         slack_token: ${{ secrets.SLACK_TOKEN }}
  #         slack_channel: "C03FN0AFT8V"
  #         # slack_username: 'Slack username'
  #         # slack_icon_emoji: ':botbot:'
  #         # suite_name: 'Playwright Test'
  #         # rules_configuration_path: 'path/to/rules/configuration/file'
  #         playwright_report_path: 'test-artifacts/**/report.json'
  #         playwright_output_dir: 'test-artifacts/**/results'