name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  deploy:
    if: always()
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
    - uses: actions/download-artifact@master
      with:
        name: playwright-report
        path: playwright-report/
    - uses: actions/configure-pages@main
    - uses: actions/upload-pages-artifact@main
      with:
        path: './playwright-report/'
    - id: deployment
      uses: actions/deploy-pages@main

    - uses: actions/checkout@v4
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: results.json
        path: ./results.json
        retention-days: 1

    - name: get properties
      id: json_properties
      uses: ActionsTools/read-json-action@main
      with:
        file_path: "results.json"
    
    - run: |
        echo ${{steps.json_properties.outputs.name}}
        echo ${{steps.json_properties.outputs.version}}
      #Test Send Slack
    # - name: Post to a Slack channel
    #   id: slack
    #   uses: slackapi/slack-github-action@v1.24.0
    #   with:
    #     # Slack channel id, channel name, or user id to post message.
    #     # See also: https://api.slack.com/methods/chat.postMessage#channels
    #     channel-id: 'C03FN0AFT8V'
    #     # For posting a rich message using Block Kit
    #     payload: |
    #       {
    #         "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
    #         "blocks": [
    #           {
    #             "type": "section",
    #             "text": {
    #               "type": "mrkdwn",
    #               "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
    #             }
    #           }
    #         ]
    #       }
    #   env:
    #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_OAUTH_TOKEN }}
      